#!/bin/bash -l

set -e

language=$(echo $(basename `git config --get remote.origin.url`) | rev | cut -d- -f1 | rev)
echo "Packaging offline buildpack for $language"

# Build offline package
rm -f ${language}_buildpack.zip
./bin/package offline

# Create buildpack on CF
cf api api.10.245.0.34.xip.io --skip-ssl-validation
cf login -u admin -p admin -o pivotal -s integration
cf delete-buildpack ${language}-test-buildpack -f
cf create-buildpack ${language}-test-buildpack ${language}_buildpack.zip 1 --enable

# RVM
export PATH=/Users/pivotal/.rvm/bin:$PATH
rvm use default

# Run specs
BUNDLE_GEMFILE=cf.Gemfile bundle
BUNDLE_GEMFILE=cf.Gemfile BUILDPACK_MODE=offline rspec cf_spec

# Release buildpack
mv ${language}_buildpack.zip /tmp/${language}_buildpack_${BUILD_NUMBER}_offline.zip
