#!/bin/bash -l

set -e

sudo ../sshuttle/sshuttle -D -v -r ubuntu@10.10.48.64 10.244.0.0/19

language=$(echo $(basename `git config --get remote.origin.url`) | rev | cut -d- -f1 | rev | cut -d. -f1)
echo "Packaging online buildpack for $language"

# Build online package
rm -f ${language}_buildpack.zip
./bin/package online

# Log in to CF
cf api api.10.244.0.34.xip.io --skip-ssl-validation
cf login -u admin -p admin 

# create and use org/space
cf create-org pivotal
cf create-space integration -o pivotal
cf target -o pivotal -s integration

# clear and reupload buildpack
cf delete-buildpack ${language}-test-buildpack -f
cf create-buildpack ${language}-test-buildpack ${language}_buildpack.zip 1 --enable

# Run specs
BUNDLE_GEMFILE=cf.Gemfile bundle
BUNDLE_GEMFILE=cf.Gemfile rspec --pattern "{integration,unit}/*_spec.rb" cf_spec

# Release buildpack
# gocd has a different var for BUILD_NUMBER
mv ${language}_buildpack.zip ${language}-online-buildpack-b${BUILD_NUMBER}.zip
