#!/bin/bash -l

set -e

buildpack_location=/tmp/buildpacks

language=$(echo $(basename `git config --get remote.origin.url`) | rev | cut -d- -f1 | rev | cut -d. -f1)
echo "Packaging online buildpack for $language"

# Build online package
rm -f ${language}_buildpack.zip
./bin/package online

# Create buildpack on CF
cf api api.10.244.0.34.xip.io --skip-ssl-validation
cf login -u admin -p admin -o pivotal -s integration
cf delete-buildpack ${language}-test-buildpack -f
cf create-buildpack ${language}-test-buildpack ${language}_buildpack.zip 1 --enable

# RVM
export PATH=/Users/pivotal/.rvm/bin:$PATH
rvm use default

# Run specs
BUNDLE_GEMFILE=cf.Gemfile bundle
BUNDLE_GEMFILE=cf.Gemfile rspec cf_spec

# Release buildpack
mkdir -p ${buildpack_location}/${language}
mv ${language}_buildpack.zip ${buildpack_location}/${language}/${language}-buildpack-b${BUILD_NUMBER}.zip